# Generated by Django 5.2.17 on 2026-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Médico'), ('ENFERMEIRA', 'Enfermeira')], max_length=20, null=True),
        ),
    ]
