services:
  # VLAN 20
  hashicorp-vault:
    image: hashicorp/vault:latest
    container_name: dados-vault
    depends_on:
      - kms-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file
      - ./vault:/vault/config
      - ./vault/start-vault.sh:/start-vault.sh:ro
    command: ["/bin/sh", "/start-vault.sh"]
    networks:
      - vlan20
    restart: unless-stopped
  
  # Vault para simular 
  kms-vault:
    image: hashicorp/vault:latest
    container_name: kms-vault
    ports:
      - "8201:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://0.0.0.0:8201"
      VAULT_API_ADDR: "http://0.0.0.0:8201"
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": {"tcp": {"address": "0.0.0.0:8201", "tls_disable": 1}}, "ui": true}'
    volumes:
      - kms_data:/vault/file
      - ./kms/start-kms.sh:/start-kms.sh:ro
    command: ["/bin/sh", "/start-kms.sh"]
    networks:
      - vlan20
    restart: unless-stopped

  postgresql:
    build: ./postgres
    container_name: dados-postgres
    environment:
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: dados_db
    command:
      - "postgres"
      - "-c"
      - "wal_level=replica"
      - "-c"
      - "archive_mode=on"
      - "-c"
      - "archive_command=pgbackrest --config=/etc/pgbackrest.conf --stanza=db_dados archive-push %p"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - pgbackrest_data:/var/lib/pgbackrest
      - ./pgbackrest/pgbackrest-dados.conf:/etc/pgbackrest.conf:ro
    networks:
      - vlan20
    restart: unless-stopped

  postgresql-keycloak:
    image: postgres:15-alpine
    container_name: dados-postgres-keycloak
    environment:
      POSTGRES_USER: keycloak_admin
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: keycloak_db
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - vlan20
    restart: unless-stopped

  # VLAN 30
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: seguranca-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://dados-postgres-keycloak:5432/keycloak_db
      KC_DB_USERNAME: keycloak_admin
      KC_DB_PASSWORD: teste
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - vlan20
      - vlan30
    restart: unless-stopped

  pgbackrest-repo:
    image: alpine:latest
    container_name: seguranca-pgbackrest
    command: ["sleep", "infinity"] 
    volumes:
      - pgbackrest_data:/var/lib/pgbackrest
    networks:
      - vlan30
      - vlan20
    restart: unless-stopped

networks:
  vlan20:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
  
  vlan30:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24
  
  vlan40:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24

volumes:
  vault_data:
  vault_config:
  kms_data:
  keycloak_db_data:
  postgres_data:
  pgbackrest_data:
  pgbackrest_config:
