services:
  nginx-proxy:
    build: ./proxy
    container_name: dmz-nginx-proxy
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - vlan10
  
  modsecurity-waf:
    image: owasp/modsecurity-crs:nginx
    container_name: dmz-modsecurity-waf
    environment:
      - PROXY_SSL=0
      - BACKEND=http://dmz-nginx-web:80
    networks:
      - vlan10
  
  nginx-web:
    image: nginx:alpine
    container_name: dmz-nginx-web
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - vlan10

networks:
  vlan10:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24