server {
    listen 80;
    server_name ${PUBLIC_HOST};
    return 301 https://${PUBLIC_HOST}${PUBLIC_HTTPS_SUFFIX}$request_uri;
}
server {
    listen 443 ssl;
    server_name ${PUBLIC_HOST};
    ssl_certificate /run/tls/public.crt;
    ssl_certificate_key /run/tls/public.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 10m;
    access_log off;
    resolver 127.0.0.11 valid=10s ipv6=off;
    location / {
        set $waf_url http://modsecurity-waf:8080;
        proxy_pass $waf_url;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        # Descarta cabeçalhos fornecidos pela Internet.
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
}
