# Generated by Django 5.2.17 on 2026-09-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Médico'), ('COORDENADOR', 'Coordenador')], max_length=20, null=True),
        ),
    ]
