# Generated by Django 5.2.17 on 2026-09-21 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['data_hora']},
        ),
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.UniqueConstraint(fields=('medico', 'data_hora'), name='consulta_unica_medico_horario'),
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to='medicos.medico'),
        ),
        migrations.AddConstraint(
            model_name='horariodisponivel',
            constraint=models.UniqueConstraint(fields=('medico', 'data_hora'), name='horario_unico_por_medico'),
        ),
    ]
