# Generated by Django 5.2.17 on 2026-09-22 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_remove_horariodisponivel_horario_unico_por_medico_and_more'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AgendamentoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames_agendados', to='pacientes.paciente')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='consultas.exame')),
            ],
            options={
                'ordering': ['data_hora'],
                'constraints': [models.UniqueConstraint(fields=('exame', 'data_hora'), name='agendamento_exame_unico_horario'), models.UniqueConstraint(fields=('paciente', 'data_hora'), name='agendamento_exame_paciente_horario')],
            },
        ),
        migrations.CreateModel(
            name='HorarioExameDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to='consultas.exame')),
            ],
            options={
                'ordering': ['data_hora'],
                'constraints': [models.UniqueConstraint(fields=('exame', 'data_hora'), name='horario_exame_unico_data_hora')],
            },
        ),
    ]
