# Generated by Django 5.2.17 on 2026-09-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_exame_agendamentoexame_horarioexamedisponivel'),
        ('coordenador', '0001_initial'),
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agendamentoexame',
            name='agendamento_exame_unico_horario',
        ),
        migrations.RemoveConstraint(
            model_name='horarioexamedisponivel',
            name='horario_exame_unico_data_hora',
        ),
        migrations.AddField(
            model_name='agendamentoexame',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_exames', to='coordenador.coordenador'),
        ),
        migrations.AddField(
            model_name='agendamentoexame',
            name='medico_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exames_agendados', to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='exame',
            name='especialidade_responsavel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='horarioexamedisponivel',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios_criados', to='coordenador.coordenador'),
        ),
        migrations.AddField(
            model_name='horarioexamedisponivel',
            name='medico_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios_exames', to='medicos.medico'),
        ),
        migrations.AddConstraint(
            model_name='agendamentoexame',
            constraint=models.UniqueConstraint(fields=('medico_responsavel', 'data_hora'), name='agendamento_exame_unico_medico'),
        ),
        migrations.AddConstraint(
            model_name='horarioexamedisponivel',
            constraint=models.UniqueConstraint(fields=('medico_responsavel', 'data_hora'), name='horario_exame_unico_medico'),
        ),
    ]
