# Generated by Django 5.2.17 on 2026-09-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_horariodisponivel_alter_consulta_options_and_more'),
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='horariodisponivel',
            name='horario_unico_por_medico',
        ),
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.UniqueConstraint(fields=('paciente', 'data_hora'), name='consulta_unica_paciente_horario'),
        ),
        migrations.AddConstraint(
            model_name='horariodisponivel',
            constraint=models.UniqueConstraint(fields=('medico', 'data_hora'), name='horario_unico_medico_data_hora'),
        ),
    ]
